# Generated by Django 5.0.1 on 2024-02-14 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cat',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cats.owner', verbose_name='Хозяин'),
        ),
        migrations.AddField(
            model_name='cat',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='cats.species', verbose_name='Породы'),
        ),
        migrations.AddField(
            model_name='cat',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='cats.tagpost', verbose_name='Теги'),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['title'], name='cats_cat_title_ca6cf9_idx'),
        ),
    ]
