# Generated by Django 5.0.1 on 2024-01-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_alter_cat_options_cat_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
