# Generated by Django 5.0.1 on 2024-01-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_cat_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]

