# Generated by Django 5.0.1 on 2024-01-15 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_species_alter_cat_is_published_cat_spec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cats.species'),
        ),
    ]
