# Generated by Django 5.0.1 on 2024-01-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_alter_cat_spec'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='cats.species'),
        ),
        migrations.AddField(
            model_name='cat',
            name='cat',
            field=models.ManyToManyField(blank=True, related_name='tags', to='cats.tagpost'),
        ),
    ]
