# Generated by Django 5.0.1 on 2024-01-31 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0010_alter_cat_options_alter_species_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
