# Generated by Django 5.0.1 on 2024-02-10 07:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0012_cat_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['title'], 'verbose_name': 'Котик', 'verbose_name_plural': 'Котики'},
        ),
        migrations.RemoveIndex(
            model_name='cat',
            name='cats_cat_time_cr_044b61_idx',
        ),
        migrations.AddField(
            model_name='cat',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cat',
            index=models.Index(fields=['title'], name='cats_cat_title_ca6cf9_idx'),
        ),
    ]
